name: second_template
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/book.png  
    - assets/R.png 
    - assets/book2.jpg 
    - assets/my_photo.jpg  
    - assets/Say.png
    - assets/sathya.jpg
    - assets/nith.png
    - assets/Rita.png
    - assets/Bott.jpg  
    - assets/R.jpg
    - assets/R(1).jpg